version: "3.9"

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=supersecret
      - AUTH_SERVICE=http://auth-service:3001
      - USER_SERVICE=http://user-service:3002
      - EXPENSE_SERVICE=http://expense-service:3003
      - NOTIFICATION_SERVICE=http://notification-service:3004
    depends_on:
      - auth-service
      - user-service
      - expense-service
      - notification-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"

  expense-service:
    build: ./services/expense-service
    ports:
      - "3003:3003"

  notification-service:
    build: ./services/notification-service
    ports:
      - "3004:3004"
